### ISSUE TITLE
Website build timing out

### ISSUE THREAD

**Issue by qualiaMachine** [carpentries-incubator/fair-explainable-ml#3]
Hi @tobyhodges, I wonder if you can assist us because we're a little stumped. Our lesson's website has been failing to build for over a week now. It seems to be a timeout issue without any specific error. I'm not sure if this is an us problem or a GitHub problem, honestly. The "[Down Detector](https://downdetector.com/status/github/)" has been spiking a bit over the past week. Has anyone else been having issues with their websites building recently? Thanks in advance.

**Comment by tobyhodges** [comment]
Looks like the problem is with the `code/upload_model_hugging_face.md` file. It looks malformed, and I think sandpaper is having difficulty parsing the Markdown as a result.

**Comment by qualiaMachine** [comment]
@tobyhodges Awesome, good catch! That file is actually not one of our official episode markdown files. It was mistakenly left in the code folder. I deleted it and the site is building now! Thanks.

I'm curious, were you able to spot that issue in the build report? Or just did some sleuthing through the repo?

**Comment by tobyhodges** [comment]
Just sleuthing, I'm afraid. I started moving files and folder out of the repo until `sandpaper::serve` worked locally.

**Comment by qualiaMachine** [comment]
Ah gotcha. Good to know! Thanks again.
